#!/bin/bash
set -euxo pipefail

echo "Running the auto-solve script..."

hasura init cli-demo
cd cli-demo
curl https://raw.githubusercontent.com/hasura/graphql-engine/master/install-manifests/docker-compose/docker-compose.yaml > docker-compose.yaml
docker-compose up -d
hasura console --address 0.0.0.0 --no-browser